<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewDelete1.aspx.cs" Inherits="GridViewDeleteasp.GridViewDelete1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting">
            <Columns>
                <asp:TemplateField HeaderText="eno">
                    <ItemTemplate>
                        <asp:Label ID="lbldelete" runat="server" Text='<%#Eval("eno")%>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ename">
                    <ItemTemplate>
                        <asp:Label ID="lbldelete2" runat="server" Text='<%#Eval("ename")%>' />

                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="salary">
                    <ItemTemplate>
                        <asp:Label ID="lbldelete3" runat="server" Text='<%#Eval("salary") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                
            </Columns>
        </asp:GridView>
    <br />
        <asp:Label ID="lblmsg" runat="server" />
    </div>
    </form>
</body>
</html>
